### PR TITLE
makes middlewares pluggable. i.e for custom oauth flows or analytics etc.

### PR DESCRIPTION
**Pull request by fredr**
Here we go! I haven't yet tested this branch agains your fork

### CODE REVIEW

**Comment by fredr** [comment]
🎉

**Comment by fredr** [comment]
I've done some testing, seems to work fine!

**Comment by fredr** [comment]
@dgaya would you like to publish this to npm? would be cool, then I can start using this package for my plugin

**Comment by dgaya** [comment]
@fredr done! 2.0.2

**Comment by fredr** [comment]
🙌

**Pull request merged**
